apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellospring-deployment
  labels:
    app: hellospring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellospring
  template:
    metadata:
      labels:
        app: hellospring
    spec:
      containers:
      - name: hello-spring
        image: db42/hellospring:desafio3-4
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: springsvc
spec:
  type: NodePort
  ports:
    - port: 8090
      nodePort: 30011
      targetPort: 8090
  selector:
    app: hellospring